# Generated by Django 6.0.4 on 2026-04-10 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador1_nombre', models.CharField(max_length=50)),
                ('jugador2_nombre', models.CharField(max_length=50)),
                ('puntuacion_j1', models.IntegerField(default=0)),
                ('puntuacion_j2', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablero', models.CharField(default='---------', max_length=9)),
                ('turno_actual', models.CharField(default='X', max_length=1)),
                ('estado', models.CharField(default='en_curso', max_length=20)),
                ('ganador', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='tic_tac_toe.torneo')),
            ],
        ),
    ]
